#!/bin/bash

# Check if TypeScript is installed
if ! command -v tsc &> /dev/null; then
    echo "TypeScript is not installed. Please install it first."
    exit 1
fi

# Compile TypeScript files
echo "Compiling TypeScript..."
tsc || { echo "Compilation failed"; exit 1; }

# Check the argument passed to the script
if [ "$1" == "install" ]; then
    echo "Running the program with 'install' command..."
    node main.js install || { echo "Failed to run the program with 'install'"; exit 1; }
elif [ "$1" == "test" ]; then
    echo "Testing"
    node main.js test || { echo "Failed to run the program with 'test'"; exit 1; }
elif [ -f "$1" ]; then
    echo "Processing file: $1"
    # Run your compiled TypeScript program with the provided file as an argument
    node main.js process "$1" || { echo "Failed to run the program"; exit 1; }

else
    # echo "Usage: ./run install or ./run URL_FILE or ./run test"
    node main.js $1
    exit 1
fi